### ISSUE TITLE
Update to Ruby 2.1 (rdoc 4.0+)

### ISSUE THREAD

**Issue by casper** [sriedel/bri#2]
Hi,

I really liked qri, but it's not available for Ruby 2.0. So I tried bri. However it doesn't work with the latest rdoc (4.1.0):

```
> bri String
/home/casper/ruby/qri/bri/lib/bri/search/class.rb:8:in `block in search': undefined method `modules' for #<RDoc::Store:0x007f56f32ada90> (NoMethodError)
        from /home/casper/ruby/qri/bri/lib/bri/search/class.rb:8:in `each'
        from /home/casper/ruby/qri/bri/lib/bri/search/class.rb:8:in `detect'
        from /home/casper/ruby/qri/bri/lib/bri/search/class.rb:8:in `search'
        from /home/casper/ruby/qri/bri/lib/bri/matcher.rb:9:in `find'
        from /home/casper/ruby/qri/bri/lib/bri.rb:39:in `ri'
        from bin/bri:46:in `<main>'
```

Any way to fix that?

**Comment by sriedel** [comment]
Yeah, I've been derelict of duties for a bit... the rdoc internals were not much fun to work with. Things do seem to have improved so I had another stab at things.

The new 0.4.1 version should work with ruby 2.6 and rdoc 6.1.
